# Generated by Django 3.2 on 2021-11-22 04:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        CITextExtension(),  # for using CICharField
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Designates whether the user can log into this admin site.',
                                                 verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                                  verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', django.contrib.postgres.fields.citext.CICharField(
                    error_messages={'unique': 'A user with that username already exists.'},
                    help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150,
                    unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                    verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=9, verbose_name='phone number')),
                ('is_employer', models.BooleanField(default=False, verbose_name='is employer')),
                ('is_job_seeker', models.BooleanField(default=False, verbose_name='is job seeker')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.Group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False,
                                      to='accounts.customuser', verbose_name='user')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
            ],
            options={
                'verbose_name': 'job seeker',
                'verbose_name_plural': 'job seekers',
                'db_table': 'job_seeker',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False,
                                      to='accounts.customuser', verbose_name='user')),
                ('company',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
            ],
            options={
                'verbose_name': 'employer',
                'verbose_name_plural': 'employers',
                'db_table': 'employer',
            },
        ),
    ]
