# Generated by Django 3.2 on 2021-11-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company',
        ),
    ]
