# Generated by Django 3.2 on 2021-12-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='new email'),
        ),
    ]
