# Generated by Django 3.2 on 2021-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
