# Generated by Django 3.2 on 2021-11-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('persian_name', models.CharField(max_length=150, verbose_name='persian name')),
                ('english_name', models.CharField(max_length=150, verbose_name='english name')),
                ('foundation', models.PositiveSmallIntegerField(choices=[(1280, 1280), (1281, 1281), (1282, 1282), (1283, 1283), (1284, 1284), (1285, 1285), (1286, 1286), (1287, 1287), (1288, 1288), (1289, 1289), (1290, 1290), (1291, 1291), (1292, 1292), (1293, 1293), (1294, 1294), (1295, 1295), (1296, 1296), (1297, 1297), (1298, 1298), (1299, 1299), (1300, 1300), (1301, 1301), (1302, 1302), (1303, 1303), (1304, 1304), (1305, 1305), (1306, 1306), (1307, 1307), (1308, 1308), (1309, 1309), (1310, 1310), (1311, 1311), (1312, 1312), (1313, 1313), (1314, 1314), (1315, 1315), (1316, 1316), (1317, 1317), (1318, 1318), (1319, 1319), (1320, 1320), (1321, 1321), (1322, 1322), (1323, 1323), (1324, 1324), (1325, 1325), (1326, 1326), (1327, 1327), (1328, 1328), (1329, 1329), (1330, 1330), (1331, 1331), (1332, 1332), (1333, 1333), (1334, 1334), (1335, 1335), (1336, 1336), (1337, 1337), (1338, 1338), (1339, 1339), (1340, 1340), (1341, 1341), (1342, 1342), (1343, 1343), (1344, 1344), (1345, 1345), (1346, 1346), (1347, 1347), (1348, 1348), (1349, 1349), (1350, 1350), (1351, 1351), (1352, 1352), (1353, 1353), (1354, 1354), (1355, 1355), (1356, 1356), (1357, 1357), (1358, 1358), (1359, 1359), (1360, 1360), (1361, 1361), (1362, 1362), (1363, 1363), (1364, 1364), (1365, 1365), (1366, 1366), (1367, 1367), (1368, 1368), (1369, 1369), (1370, 1370), (1371, 1371), (1372, 1372), (1373, 1373), (1374, 1374), (1375, 1375), (1376, 1376), (1377, 1377), (1378, 1378), (1379, 1379), (1380, 1380), (1381, 1381), (1382, 1382), (1383, 1383), (1384, 1384), (1385, 1385), (1386, 1386), (1387, 1387), (1388, 1388), (1389, 1389), (1390, 1390), (1391, 1391), (1392, 1392), (1393, 1393), (1394, 1394), (1395, 1395), (1396, 1396), (1397, 1397), (1398, 1398), (1399, 1399), (1400, 1400)], verbose_name='year')),
                ('site', models.URLField(blank=True, verbose_name='site')),
                ('logo', models.ImageField(upload_to='company/logos/', verbose_name='logo')),
                ('banner', models.ImageField(upload_to='company/banners/', verbose_name='banner')),
                ('number_of_employees', models.PositiveSmallIntegerField(verbose_name='number of employees')),
                ('description', models.TextField(verbose_name='description')),
                ('introduction', models.TextField(blank=True, verbose_name='introduction')),
                ('culture', models.TextField(blank=True, verbose_name='culture')),
                ('advantage', models.TextField(blank=True, verbose_name='advantage')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='address.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('type', models.CharField(max_length=60, verbose_name='type')),
            ],
            options={
                'verbose_name': 'company type',
                'verbose_name_plural': 'company types',
                'db_table': 'company_type',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('type', models.CharField(max_length=60, verbose_name='type')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('image', models.ImageField(upload_to='employee/images/', verbose_name='image')),
                ('description', models.TextField(verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company', verbose_name='company')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='company.employeetype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='company.companytype', verbose_name='type'),
        ),
    ]
