# Generated by Django 3.2 on 2021-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='company/banners/', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='logo'),
        ),
    ]
