# Generated by Django 3.2 on 2021-11-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_employer_company'),
        ('company', '0002_auto_20211123_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.employer', verbose_name='employer'),
        ),
    ]
