# Generated by Django 3.2 on 2021-11-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employer_user'),
        ('company', '0003_company_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.employer', verbose_name='employer'),
        ),
    ]
