# Generated by Django 3.2 on 2021-11-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='type',
            field=models.CharField(max_length=60, unique=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='type',
            field=models.CharField(max_length=60, unique=True, verbose_name='type'),
        ),
    ]
