# Generated by Django 3.2 on 2021-11-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=48, verbose_name='name')),
            ],
            options={
                'verbose_name': 'job category',
                'verbose_name_plural': 'job categories',
                'db_table': 'job_category',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('title', models.CharField(max_length=48, verbose_name='name')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('title', models.CharField(max_length=48, verbose_name='name')),
                ('cooperation_type', models.PositiveSmallIntegerField(choices=[(0, 'full time'), (1, 'part time')], verbose_name='cooperation type')),
                ('remote_available', models.BooleanField(default=False, verbose_name='remote available')),
                ('work_experience', models.PositiveSmallIntegerField(choices=[(0, 'not important'), (1, 'less than three'), (2, 'between three and six'), (3, 'more than six')], default=0, verbose_name='work experience')),
                ('salary_agreement', models.BooleanField(default=True, verbose_name='salary agreement')),
                ('salary', models.PositiveIntegerField(verbose_name='salary')),
                ('description', models.TextField(verbose_name='description')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'not important'), (1, 'male'), (2, 'female')], verbose_name='sex')),
                ('at_least_degree', models.PositiveSmallIntegerField(choices=[(0, 'not important'), (1, 'associate'), (2, 'bachelor')], verbose_name='at least degree')),
                ('military_service_status', models.PositiveSmallIntegerField(choices=[(0, 'not important'), (1, 'served or exempt')], verbose_name='military service status')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job.jobcategory', verbose_name='category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='address.city', verbose_name='city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company', verbose_name='company')),
                ('required_skills', models.ManyToManyField(related_name='jobs', to='job.Skill', verbose_name='required skills')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
            },
        ),
    ]
