# Generated by Django 3.2 on 2021-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(null=True, verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=48, unique=True, verbose_name='name'),
        ),
    ]
